### ISSUE TITLE
Bug in actel version 1.3.0.9015"

### ISSUE THREAD

**Issue by LeneSo** [hugomflavio/actel#148] opened 2024-12-03 13:24 UTC
I downloaded the latest actel version ‘1.3.0.9015’ from github using the function remotes::install_github("hugomflavio/actel", build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE).
When I run the function migration with “method = first to first” on some data, it starts as normal, but then I get this error message:
 
```
+   migration(tz = 'Europe/Belfast', 
+             section.order = NULL, datapack = NULL, 
+             success.arrays = NULL, 
+             max.interval = 60, 
+             min.total.detections = 2, min.per.event = c(1, 1), 
+             start.time = NULL, stop.time = NULL, 
+             speed.method = 'first to first', 
+             speed.warning = 3, speed.error = 3, 
+             jump.warning = 2, jump.error = 2, 
+             inactive.warning = 2, inactive.error = 2, 
+             exclude.tags = NULL, 
+             report = TRUE, auto.open = TRUE, 
+             discard.orphans = FALSE, discard.first = NULL, 
+             save.detections = FALSE, 
+             if.last.skip.section = FALSE, 
+             disregard.parallels = TRUE, 
+             GUI = 'needed', print.releases = TRUE, 
+             detections.y.axis = 'stations') 
```
Warning: GUI is set to 'needed' but package 'gWidgets2tcltk' is not available. Please install it if you intend to run the GUI. Disabling GUI (i.e. GUI = 'never') for the current run.
M: Importing data. This process may take a while.
M: No Code.space column was found in the biometrics. Assigning code spaces based on detections.
M: Number of target tags: 100.
M: Compiling detections...
M: Matching detections with deployment periods.
  |============================================================| 100%
M: Number of ALS: 5 (of which 0 had no detections)
M: Data time range: 2024-04-21 06:04:17 to 2024-09-19 10:57:45 (Europe/Belfast).
M: File 'distances.csv' found, activating speed calculations.
M: Extracting relevant detections...
Stray tags were detected in your study area. Would you like to save a summary to stray_tags.csv?(y/n) y
M: Data successfully imported!
Warning: 'success.arrays' was not defined. Assuming success if the tags are last detected at array A4.
M: Creating movement records for the valid tags.
  |============================================================| 100%
M: Checking movement events quality.
Advarsel: Tag A69-1604-34982 (1/70) had an average speed of 3.81 m/s from valid event 3 to 4 (A3 -> A2).
Advarsel: Tag A69-1604-34982 (1/70) had an average speed of 677.89 m/s from valid event 4 to 5 (A2 -> A3).
Advarsel: Tag A69-1604-34982 (1/70) had an average speed of 11.69 m/s from valid event 7 to 8 (A2 -> A3).
Advarsel: Tag A69-1604-34982 (1/70) had an average speed of 3.32 m/s from valid event 10 to 11 (A3 -> A2).
Warning: Tag A69-1604-34982 (1/70) had an average speed higher than 3 m/s in 11 events (of which the first 4 are displayed above).
Fejl i paste0(...) : argument mangler, uden nogen standard 
(english: "Error in paste0(...): argument is missing, with no default")
 
A fatal exception occurred!

**Comment by hugomflavio** [comment] 2024-12-03 15:11
Hi Lene, thanks for reporting this!

Could you run this same analysis but in debug mode? All you need to do is run

`options(actel.debug = TRUE)`

before running your analysis again. This will show exactly which internal function caused the crash. The last few lines of the output should be enough to figure out what crashed.

**Comment by LeneSo** [comment] 2024-12-04 10:01
I ran actel with the debug option, but doesn't seem that it provided any more insights?:
M: Checking movement events quality.
Debug: Checking movement quality for tag A69-1604-34982.
Debug: Running checkMinimumN
Debug: Running checkFirstMove.
Debug: Running checkImpassables.
Debug: Running checkJumpDistance.
Debug: Running simplifyMovements.
Debug: Running movementTimes.
Debug: Running movementSpeeds.
Debug: Running speedReleaseToFirst.
Debug: Running checkSpeeds.
Advarsel: Tag A69-1604-34982 (1/70) had an average speed of 3.81 m/s from valid event 3 to 4 (A3 -> A2).
Advarsel: Tag A69-1604-34982 (1/70) had an average speed of 677.89 m/s from valid event 4 to 5 (A2 -> A3).
Advarsel: Tag A69-1604-34982 (1/70) had an average speed of 11.69 m/s from valid event 7 to 8 (A2 -> A3).
Advarsel: Tag A69-1604-34982 (1/70) had an average speed of 3.32 m/s from valid event 10 to 11 (A3 -> A2).
Warning: Tag A69-1604-34982 (1/70) had an average speed higher than 3 m/s in 11 events (of which the first 4 are displayed above).
Fejl i paste0(...) : argument mangler, uden nogen standard

A fatal exception occurred!

**Comment by hugomflavio** [comment] 2024-12-04 11:33
#149 is now being tested. Once it passes the tests it will be merged into the master. If you want to give it a try right away, you can install the version being tested directly with:

```r
remotes::install_github("hugomflavio/actel",
                        ref = "issue_148",
                        build_opts = c("--no-resave-data", "--no-manual"),
                        build_vignettes = TRUE)
```

**Comment by hugomflavio** [comment] 2024-12-04 13:58
Fix is now merged with master. Could you confirm this resolves your problem?

Thanks!

**Comment by hugomflavio** [comment] 2024-12-05 14:02
Did you get any warnings/messages when 1) creating the distances matrix, and/or 2) relating to the distances matrix during this analysis? I can see where the issue is, but I wouldn't expect a fail-safe to be necessary there... so I'd like to understand what happened better. If you could upload your distances matrix here that would be perfect too.


For my reference, this is the line: https://github.com/hugomflavio/actel/blob/0a7814041287421f9870683ad481d80fa5ee33e4/R/check.R#L719

**Comment by hugomflavio** [comment] 2024-12-05 14:27
Does the issue go away if you replace the NAs in the diagonal line with 0's? The distances matrix shouldn't have any NAs (see template [here](https://hugomflavio.github.io/actel-website/manual-distances.html)).

**Comment by hugomflavio** [comment] 2024-12-06 10:28
Awesome! :)

**Closed** 2024-12-06 10:28 UTC
Labels: bug
